export enum RepositoryCategory {
  WEB_DEVELOPMENT = "WEB_DEVELOPMENT",
  MOBILE_DEVELOPMENT = "MOBILE_DEVELOPMENT",
  BACKEND_SYSTEMS = "BACKEND_SYSTEMS",
  DATA_SCIENCE = "DATA_SCIENCE",
  FULL_STACK = "FULL_STACK",
}
